# tohle vypise vsechny uzivatele kteri nekdy neco koupili za nedefaultni cenu 

PREFIX ex: <http://example.org/whiskeyman/> 
PREFIX schema: <http://schema.org> 



SELECT ?name
WHERE {
    ?trans a ex:Transaction ;
        schema:Price ?realPrice ;
        ex:AmmountMl ?amount ;
        ex:TransactionMadeBY ?buyer ;
        ex:Bottle ?bottle .

    ?bottle a ex:Bottle ;
        ex:PriceForML  ?priceMl .

    FILTER(?realPrice != (?priceMl * ?amount)).

    ?buyer schema:name ?name
}
GROUP BY  ?name