# vypise vsechny regiony od kterych uzivatel koupil lahev

PREFIX ex: <http://example.org/whiskeyman/> 
PREFIX schema: <http://schema.org> 

SELECT ?user (GROUP_CONCAT(?region_name;SEPARATOR=", ") AS ?regions)
WHERE {
  	?tr a ex:Transaction;
       	ex:TransactionMadeBY ?person;
  		ex:Bottle ?bottle.
  
    ?person schema:name ?user.
    ?bottle ex:DescribedBy ?BottleDescription.
    ?BottleDescription ex:Distillery ?destilery.
    ?destilery ex:Region ?region.
    ?region schema:name ?region_name.
}
GROUP BY ?user
ORDER BY ?user