#zisk nfc tagu zákazníka k dané transakci

PREFIX ex: <http://example.org/whiskeyman/> 
PREFIX schema: <http://schema.org> 


SELECT (GROUP_CONCAT(?nfcCode;SEPARATOR=", ") AS ?nfcCodes) ?name ?transaction ?bottleBought ?amount 
WHERE {
	?transaction a ex:Transaction;
              ex:AmmountMl ?amount;
              ex:Bottle	?bottleBought;
              ex:TransactionMadeBY ?user.
    ?user 	schema:name ?name;
  			ex:NfcTag ?nfctag.
  	?nfctag schema:Text ?nfcCode.  	
}
GROUP BY ?transaction ?name  ?bottleBought ?amount 