#Vypise vsechny lahve co jsou na sklade se vsema informacema o lahvich i o destlerkach

PREFIX ex: <http://example.org/whiskeyman/> 
PREFIX schema: <http://schema.org> 

SELECT  ?bottleName ?DestileryName (GROUP_CONCAT(?regionName;SEPARATOR=", ") AS ?regions)
WHERE {
    ?d a ex:Bottle ;
           	ex:InStock true ;
  			ex:DescribedBy ?bottleDes .
    ?bottleDes schema:name ?bottleName;
            ex:Distillery ?destilery.
  	?destilery schema:name ?DestileryName;
            ex:Region ?region.
  	?region schema:name ?regionName. 
}
GROUP BY ?bottleName ?DestileryName
ORDER BY ?bottleName 

