#Vypise vsechny lahve co jsou na sklade se vsema informacema o lahvich i o destlerkach

PREFIX vcard: <http://www.w3.org/2006/vcard/ns>
PREFIX dcterms: <http://purl.org/dc/terms>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dcat: <http://www.w3.org/ns/dcat> 
PREFIX npg: <http://ns.nature.com/terms/year> 
PREFIX bevon: <http://rdfs.co/bevon/latest/html> 
PREFIX cis: <http://dati.beniculturali.it/cultural-ON/cultural-ON.owl> 
PREFIX schema: <http://schema.org> 
PREFIX cerif: <http://www.eurocris.org/ontologies/cerif/1.3> 
PREFIX cd: <http://citydata.wu.ac.at/ns#>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT  ?bottleName ?DestileryName (GROUP_CONCAT(?regionName;SEPARATOR=", ") AS ?regions)
WHERE {
    ?bottle a bevon:Bottle ;       
           	cis:inStock true ;
  			dcat:describe ?bottleDes .
    ?bottleDes dcterms:name ?bottleName;
            dcat:destilled ?destilery.
  	?destilery dcterms:name ?DestileryName;
            dcterms:hailsFrom ?region.
  	?region dcterms:name ?regionName. 
}
GROUP BY ?bottleName ?DestileryName
ORDER BY ?bottleName    

